
function start()

    // window.alert("Thanks for visiting")

    // let ans=window.confirm("are you sure? ")
    // console.log(ans)

    // let  ans= window.prompt("enter your name")
    // console.log(ans);

    //    let ans =parseInt(prompt("enter no 1"))
    //    let ans2= parseInt(prompt("enter no 2"))
    //    alert(ans+ans2)


    //   let  ans= confirm("do you like my website")
    //   if(ans==true){
    //      alert("thank for visiting")
    //   }
    //   else{
    //      alert("sorry for here that")
    //

   var a = 40
       b = 23
       if{
        ("the value of sum number")
        
       }

}


start();