// let go=()=>{
//     let ans = document.querySelector("#text")

//     ans.innerHTML="Hello javscript"

// }
// let go1=()=>{
//     let ans1 = document.querySelector("#text1")

//     ans1.innerHTML="Hello world"
// }

 let redclr=()=>{
    let box=document.querySelector("#box");
    box.style.backgroundColor="red"}

 let leaveclr=()=>{
    let box=document.querySelector("box");
    box.style.backgroundColor="green"}
